@jwt = Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2OTM1MjgzNDV9.HuiFjO_nD1JwMd3tMVxCA5a_xevH3Xvng4DLQt3COu4

# Users 
### create (aka SIGN UP/ACCOUNT CREATION)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password" 
}

### destroy
DELETE http://localhost:3000/users/3.json
Authorization: {{jwt}}

# Sessions (aka LOGGING IN)
### create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

# Students
### create
POST http://localhost:3000/students.json
Authorization: {{jwt}}
Content-Type: application/json

{
  "first_name": "test",
  "last_name": "test",
  "email": "test",
  "phone_number": "123456789",
  "short_bio": "test",
  "linkedin_url": "test",
  "twitter_handle": "test",
  "website_url": "test",
  "online_resume_url": "test",
  "github_url": "test",
  "photo": "test"
}

# Experiences
### create
POST http://localhost:3000/experiences.json
Authorization: {{jwt}}
Content-Type: application/json

{
  "student_id": 1,
  "start_date": "01/01/01",
  "end_date": "12/31/01", 
  "job_title": "test",
  "company_name": "test",
  "details": "test" 
}



